[package]
name = "accord-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.14.3", features = ["raw"] }

[dev-dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
